#!/usr/bin/env bash

get_script_dir () {
     local SOURCE="${BASH_SOURCE[0]}"
     while [ -h "$SOURCE" ]; do
          local DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          local SOURCE="$( readlink "$SOURCE" )"
          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
     done

     cd -P "$( dirname "$SOURCE" )"
     pwd
}

SCRIPT_DIR=$(get_script_dir)

DOCKER_CMD="docker run --rm -it --privileged --device=/dev/ttyUSB0 -e HOST_USER_ID=$(id -u) -e HOST_USER_GID=$(id -g) -w /src -v ${SCRIPT_DIR}/../src:/src -v esp-idf:/esp jasonvasquez/esp-idf"

build () {
    ${DOCKER_CMD} make
}
flash () {
    ${DOCKER_CMD} make flash
}
monitor () {
    ${DOCKER_CMD} make monitor
}
shell () {
    ${DOCKER_CMD} bash
}
usage () {
    echo "here's some help"
}




for arg in $@
do
    case $arg in
        "build" )
            build ;;
        "flash" )
            flash ;;
        "monitor" )
            monitor ;;
        "shell" )
            shell ;;
        "help" )
            usage ;;
    esac
done